### ISSUE TITLE
iterator invalid

### ISSUE THREAD

**Issue by maddin200** [dperaltac/mpi-afis#3]
mpi-afis-master/Parallel/ParallelSlave.cpp line 84 
fname not assigned
code :
if(fp_list[i][j]->readFile(filenames[begin+i], quality))
				cerr << "WARNING: Process " << getProcessID() << ": Error when reading file " + *fname << endl;

**Comment by dperaltac** [comment]
Fixed in commit 38e55c104e6033b6b5d5f5e13be426d1ed8a23e2
